### ISSUE TITLE
ADD Tenant CRD

### ISSUE THREAD

**Issue by frezes** [WizTelemetry/whizard#10]
*What problem are you trying to solve?*

**允许指定 ingestor/store 来将数据写入不同的bucket 中；**
**ruler/ingestor 创建/删除 通过 ThanosTenant 进行联动，解耦ks cluster；**

*Describe the solution you'd like:*

CRD 描述:
 ```yaml
apiVersion: monitoring.paodin.io/v1alpha1
kind: ThanosTenant
metadata:
	name: ClusterName
spec:
	tanantID: xxx （可为空，为空则ClusterName生成）
	service: 	serviceName
		name:
		namespace:   
	ingestor?:  ingestorName,允许指定ingestor？
	store?:       storeName ，允许指定Store？ 			
	（ingestor 与store 组件关联，二选一，指定store 则由auto-scaler 进行调度ingestor）
status:
	tanantHeader: cluster 			来自于service spec字段
	tanantID: xxx			
	ingestor: xxxx-ingestor			
	ruler: xxxx-rule				根据thanetName生成
	store: xxxx-store
 ```

补充：
* 初始化：
    * 使用工具为已有的集群自动生成ThanosTenant，指定service、store等
* 新增：
    * 尽量页面配置，在集群加入时勾选多集群监控，详情页自动生成变动的yaml文件
    * 增加开关，允许Watch kubesphere cluster Add/Del Event 同步ThanosTenant
* 删除：

后续扩展：
  * auth
